import type { WireInstructions } from "@/services/team-14-payments";
import { Disclaimer } from "@/components/legal/disclaimer";

type Props = {
  wire: WireInstructions;
};

// Wire Instructions Display — renders the escrow account strings generated by
// Team 14 plus the mandatory "confirm by phone" disclaimer from the Legal
// Disclaimer Library (key: `wire-instructions`). Reference is the dealId per
// the generator so buyer-side ACH reconciliation matches.
export function WireInstructionsDisplay({ wire }: Props) {
  const rows: Array<[label: string, value: string, testid: string]> = [
    ["Beneficiary", wire.beneficiary, "wire-beneficiary"],
    ["Bank", wire.bankName, "wire-bank"],
    ["Routing", wire.routingNumber, "wire-routing"],
    ["Account", wire.accountNumber, "wire-account"],
    ["Reference", wire.reference, "wire-reference"],
  ];

  return (
    <section
      data-testid="wire-instructions"
      className="rounded-lg border border-border bg-background p-4-800-950"
    >
      <header className="mb-3">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
          Wire instructions
        </h2>
      </header>
      <dl className="grid grid-cols-[auto,1fr] gap-x-6 gap-y-1 text-sm">
        {rows.map(([label, value, testid]) => (
          <ItemRow key={testid} label={label} value={value} testid={testid} />
        ))}
      </dl>
      <Disclaimer context="wire-instructions" className="mt-3 text-xs text-muted-foreground" />
    </section>
  );
}

function ItemRow({
  label,
  value,
  testid,
}: {
  label: string;
  value: string;
  testid: string;
}) {
  return (
    <>
      <dt className="text-muted-foreground">{label}</dt>
      <dd
        data-testid={testid}
        className="text-right font-mono text-sm"
      >
        {value}
      </dd>
    </>
  );
}
